config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :jmxs
  resources :load_tests
  resources :master_configurations
  resources :slave_servers

  post "/jmxs/delete", to: "jmxs#destroy"
  post "/jmeters/start", to: "jmeters#start"
  post "/jmeters/stop", to: "jmeters#stop"

  get "homepage/index"

  root "homepage#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/slave_server.rb
# frozen_string_literal: true

class SlaveServer < ApplicationRecord
  validates :host, :username, :password, :port, :slave_type, :slave_status, presence: true
end

app/controllers/slave_servers_controller.rb
# frozen_string_literal: true

class SlaveServersController < ApplicationController
  def index
    @slave_servers = SlaveServer.all
  end

  def show
    @slave_server = SlaveServer.find(params[:id])
  end

  def new
    @slave_server = SlaveServer.new
  end

  def create
    @slave_server = SlaveServer.new(slave_server_params)
    if @slave_server.save
      redirect_to @slave_server
    else
      render "new"
    end
  end

  def update
    @slave_server = SlaveServer.find(params[:id])
    if @slave_server.update(slave_server_params)
      redirect_to @slave_server
    else
      render "edit"
    end
  end

  def edit
    @slave_server = SlaveServer.find(params[:id])
  end

  def destroy
    @slave_server = SlaveServer.find(params[:id])
    @slave_server.destroy

    redirect_to slave_servers_path
  end

  private

    def slave_server_params
      params.require(:slave_server).permit(:host, :username, :password, :port, :slave_type, :slave_status)
    end
end

app/helpers/slave_servers_helper.rb
# frozen_string_literal: true

module SlaveServersHelper
end

app/views/slave_servers/edit.html.erb
<div class="container mt-2">
  <div class="col-sm pb-4">
    <h2 class="text-left">Edit Slave Server</h2>
  </div>
  <%= form_with(model: @slave_server, local: true) do |form| %>

     <div class="form-group">
      <%= form.label :host %>
      <%= form.text_field :host, class: "form-control", placeholder: "Host/IP" %>
    </div>

    <div class="form-group">
      <%= form.label :username %>
      <%= form.text_field :username, class: "form-control", placeholder: "Username" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control", placeholder: "Password", value: "#{@slave_server.password}" %>
    </div>

    <div class="form-group">
      <%= form.label :port %>
      <%= form.text_field :port, class: "form-control", placeholder: "Port" %>
    </div>

    <div class="form-group">
      <%= form.label :slave_type %>
      <%= form.select(:slave_type, {}, {}, {class: "form-control custom-select"}) do %>
        <%= options_for_select([['Stress Test', 'stress-test'], ['Load Test', 'load-test']], @slave_server.slave_type) %>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.label :slave_status %>
      <%= form.select(:slave_status, {}, {}, {class: "form-control custom-select"}) do %>
        <%= options_for_select([['Activate', 'ON'], ['Deactivate', 'OFF']], @slave_server.slave_status) %>
      <% end %>
    </div>

    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Delete', slave_server_path(@slave_server),
      method: :delete,
      data: { confirm: 'Are you sure?' },
      class: "btn btn-danger"
    %>
<% end %>
</div>

app/views/slave_servers/index.html.erb
<div class="container mt-2">
  <div class="row col-12" >
    <h1 class="col-6 text-left" >Slave Server</h1>
    <div class="col-6 text-right" >
      <%= link_to 'New Slave Server', new_slave_server_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-hover text-center table-striped">
      <tr class="table-info">
        <th>Host/IP</th>
        <th>Username</th>
        <th>Port</th>
        <th>Slave Type</th>
        <th>Slave Status</th>
        <th>Action</th>
      </tr>

      <% @slave_servers.each do |slave_server| %>
        <tr>
          <td><%= slave_server.host %></td>
          <td><%= slave_server.username %></td>
          <td><%= slave_server.port %></td>
          <td><%= slave_server.slave_type %></td>
          <td><%= slave_server.slave_status %></td>
          <td>
            <%= link_to 'Edit', edit_slave_server_path(slave_server), class: "btn btn-warning" %>
            <%= link_to 'Delete', slave_server_path(slave_server),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: "btn btn-danger"
            %>
          </td>

        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/slave_servers/new.html.erb
<div class="container mt-2">
  <div class="col-sm pb-4">
    <h2 class="text-left">Add Slave Server</h2>
  </div>
  <%= form_with scope: :slave_server, url: slave_servers_path, local: true do |form| %>

    <div class="form-group">
      <%= form.label :host %>
      <%= form.text_field :host, class: "form-control", placeholder: "Host/IP" %>
    </div>

    <div class="form-group">
      <%= form.label :username %>
      <%= form.text_field :username, class: "form-control", placeholder: "Username" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>

    <div class="form-group">
      <%= form.label :port %>
      <%= form.text_field :port, class: "form-control", placeholder: "Port" %>
    </div>

    <div class="form-group">
      <%= form.label :slave_type %>
      <%= form.select(:slave_type, {}, {}, {class: "form-control custom-select"}) do %>
        <%= options_for_select([['Stress Test', 'stress-test'], ['Load Test', 'load-test']]) %>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.label :slave_status %>
      <%= form.select(:slave_status, {}, {}, {class: "form-control custom-select"}) do %>
        <%= options_for_select([['ON', 'ON'], ['OFF', 'OFF']], @slave_server.slave_status) %>
      <% end %>
    </div>

    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', slave_servers_path, class: "btn btn-warning" %>
  <% end %>
</div>

app/views/slave_servers/show.html.erb
<div class="container mt-2">
  <p>
  <strong>Host/IP:</strong>
  <%= @slave_server.host %>
  </p>

  <p>
  <strong>Username:</strong>
  <%= @slave_server.username %>
  </p>

  <p>
  <strong>Port Number:</strong>
  <%= @slave_server.port %>
  </p>

  <p>
  <strong>Slave Type:</strong>
  <%= @slave_server.slave_type %>
  </p>

  <p>
  <strong>Slave Status:</strong>
  <%= @slave_server.slave_status %>
  </p>

  <%= link_to 'Back', slave_servers_path, class: "btn btn-primary" %>
  <%= link_to 'Delete', slave_server_path(@slave_server),
    method: :delete,
    data: { confirm: 'Are you sure?' },
    class: "btn btn-danger"
  %>
</div>