config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :jmxs
  resources :load_tests
  resources :master_configurations
  resources :slave_servers

  post "/jmxs/delete", to: "jmxs#destroy"
  post "/jmeters/start", to: "jmeters#start"
  post "/jmeters/stop", to: "jmeters#stop"

  get "homepage/index"

  root "homepage#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/master_configuration.rb
# frozen_string_literal: true

class MasterConfiguration < ApplicationRecord
end

app/controllers/master_configurations_controller.rb
# frozen_string_literal: true

class MasterConfigurationsController < ApplicationController
  def index
    @master_configuration = MasterConfiguration.last
  end

  def create
    @master_configuration = MasterConfiguration.new(master_configuration_params)
    if @master_configuration.save
      redirect_to "/master_configurations"
    else
      render "index"
    end
  end

  private

    def master_configuration_params
      params.require(:master_configuration).permit(
        :master_server_host,
        :master_server_docker_host,
        :master_server_username,
        :master_server_port,
        :master_server_password,
        :master_server_jmeter_run_command,
        :influxdb_host,
        :influxdb_port,
        :telegram_credential,
        :telegram_perf_group_id
      )
    end
end

app/helpers/master_configurations_helper.rb
# frozen_string_literal: true

module MasterConfigurationsHelper
end

app/views/master_configurations/index.html.erb
<div class="container mt-2 pb-3">
  <div class="col-sm pb-4">
    <h2 class="text-left">Master Configuration</h2>
  </div>
  <%= form_with scope: :master_configuration, url: master_configurations_path, local: true do |form| %>

    <div class="form-group">
      <%= form.label :master_server_host, "Master Server Host" %>
      <%= form.text_field :master_server_host, class: "form-control", placeholder: "IP/Hostname" %>
    </div>

    <div class="form-group">
      <%= form.label :master_server_username, "Master Server Username" %>
      <%= form.text_field :master_server_username, class: "form-control", placeholder: "Username" %>
    </div>

    <div class="form-group">
      <%= form.label :master_server_port, "Master Server Port" %>
      <%= form.text_field :master_server_port, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :master_server_password, "Master Server Password" %>
      <%= form.password_field :master_server_password, class: "form-control", value: "#{@master_configuration.master_server_password if @master_configuration}" %>
    </div>

    <div class="form-group">
      <%= form.label :master_server_jmeter_run_command, "Jmeter Run Command" %>
      <%= form.text_field :master_server_jmeter_run_command, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :influxdb_host, "Influxdb Host" %>
      <%= form.text_field :influxdb_host, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :influxdb_port, "Influxdb Port" %>
      <%= form.text_field :influxdb_port, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :telegram_credential, "Telegram Credential" %>
      <%= form.password_field :telegram_credential, class: "form-control", value: "#{@master_configuration.telegram_credential if @master_configuration}" %>
    </div>

    <div class="form-group">
      <%= form.label :telegram_perf_group_id, "Perf Group ID" %>
      <%= form.text_field :telegram_perf_group_id, class: "form-control" %>
    </div>

    <%= form.submit "Save Configuration", class: "btn btn-primary" %>
  <% end %>
</div>