config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :jmxs
  resources :load_tests
  resources :master_configurations
  resources :slave_servers

  post "/jmxs/delete", to: "jmxs#destroy"
  post "/jmeters/start", to: "jmeters#start"
  post "/jmeters/stop", to: "jmeters#stop"

  get "homepage/index"

  root "homepage#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/load_test.rb
# frozen_string_literal: true

class LoadTest < ApplicationRecord
  include Notification

  has_one_attached :jmx_script
  has_one_attached :csv
  has_one_attached :artifact

  validates :jmx_id, :squad, :threshold, presence: true
  validates :csv, attached: { message: "The file you choose need CSV" },
    file: { ext: ".csv", message: "The file extension need to be .csv" },
    if: :csv_needed?
  validate :csv_matched?, :csv_rows_less?
  before_save :insert_name, :insert_params, :capitalize_squad, :attach_jmx_script

  self.per_page = 10

  def insert_name
    self.jmx_name = Jmx.find(self.jmx_id).name
  end

  def capitalize_squad
    self.squad.upcase!
  end

  def csv_needed?
    Jmx.find(self.jmx_id).script.download.include? "CSV" if self.jmx_id?
  end

  def csv_matched?
    csv = self.csv
    return unless csv_needed? && csv.attached?
    errors[:csv] << "CSV file not matched" unless csv.download.split.first.split(/;|,/).size == Jmx.find(self.jmx_id).script.download.match(/variableNames\">(.+)</)[1].split(",").size
  end

  def csv_rows_less?
    csv = self.csv
    return unless csv_needed? && csv.attached?
    raw_csv_size = self.csv.download.split(/\r\n|\n/).size
    csv_on_jmx = Jmx.find(self.jmx_id).script.download.match(/variableNames\">(.+)</)[1].split(",")
    uploading_csv = self.csv.download.split.first.split(/;|,/)
    if csv_on_jmx == uploading_csv
      @csv_rows = raw_csv_size-1
    else
      @csv_rows = raw_csv_size
    end
    @csv_rows
    errors[:csv] << "CSV: Minimum Rows are 10" if @csv_rows < 10
  end

  def insert_params
    self.threads = 10
    self.ramp = 1
    self.duration = 60
    self.timeouts = 10000
  end

  def attach_jmx_script
    self.jmx_script.attach(io: StringIO.new(Jmx.find(self.jmx_id).script.download), filename: self.jmx_name)
  end

  def notif_error
    notif_load_test_error(self.telegram_id)
  end
end

app/controllers/load_tests_controller.rb
# frozen_string_literal: true

class LoadTestsController < ApplicationController
  def index
    if search_params
      load_tests = LoadTest.where("jmx_name Like ?", "%#{search_params[:search]}%")
    else
      load_tests = LoadTest
    end
    @load_tests = load_tests.page(params[:page]).order(created_at: :desc)
    @load_tests
  end

  def new
    @load_test = LoadTest.new
  end

  def create
    @load_test = LoadTest.new(load_test_params)
    if @load_test.save
      redirect_to @load_test
    else
      render "new"
    end
  end

  def update
    @load_test = LoadTest.find(params[:id])
    if @load_test.update(load_test_params)
      redirect_to @load_test
    else
      render "edit"
    end
  end

  def edit
    @load_test = LoadTest.find(params[:id])
  end

  def show
    load_test_id = params[:id]
    @load_test = LoadTest.find(load_test_id)
    labels = LoadTestReport.where(load_test_id: load_test_id).pluck(:label).uniq
    @load_test_reports = []
    labels.each do |label|
      @load_test_reports << LoadTestReport.where(label: label).where(load_test_id: load_test_id).last
    end
  end

  def destroy
    @load_test = LoadTest.find(params[:id])
    @load_test.destroy

    redirect_to load_tests_path
  end

  private

    def load_test_params
      params.require(:load_test).permit(:jmx_id, :csv, :squad, :note, :telegram_id, :threshold)
    end

    def search_params
      if params[:jmeter]
        params.require(:jmeter).permit(:search)
      end
    end
end

app/helpers/load_tests_helper.rb
# frozen_string_literal: true

module LoadTestsHelper
end

app/views/load_tests/edit.html.erb
<div class="container mt-2">
  <div class="col-sm pb-4">
    <h2 class="text-left">Edit Load Test</h2>
  </div>
  <%= form_with(model: @load_test, local: true) do |form| %>

    <div class="form-group">
      <%= form.label :jmx_id, "Choose JMX file" %>
      <%= form.select "jmx_id", Jmx.all.collect {|jmx| [jmx.name, jmx.id]}, {}, class: "form-control custom-select" %>
    </div>

    <div class="form-group">
      <%= form.label :csv, "Choose CSV file" %>
      <div class="custom-file">
        <%= form.file_field :csv, class: "custom-file-input" %>
        <label class="custom-file-label" for="csvFile">Choose CSV file</label>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :threshold %>
      <%= form.text_field :threshold, class: "form-control", placeholder: "in milliseconds" %>
    </div>

    <div class="form-group">
      <%= form.label :squad %>
      <%= form.text_field :squad, class: "form-control", placeholder: "Squad" %>
    </div>

    <div class="form-group">
      <%= form.label :telegram_id, "Telegram ID" %>
      <%= form.text_field :telegram_id, class: "form-control", placeholder: "Note" %>
    </div>

    <div class="form-group">
      <%= form.label :note %>
      <%= form.text_area :note, class: "form-control", placeholder: "Note" %>
    </div>

    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Delete', load_test_path(@load_test),
      method: :delete,
      data: { confirm: 'Are you sure?' },
      class: "btn btn-danger"
    %>
<% end %>
</div>

app/views/load_tests/index.html.erb
<div class="container mt-2">
  <div class="container col-12">
      <form class="form-inline my-2 my-lg-0 pb-2">
        <div class="row col 12">
          <h1 class="text-left col-6">Load Test</h1>
          <div class="text-right col-6">
            <input class="form-control mr-sm-2" type="search" name="jmeter[search]" placeholder="Keywords" aria-label="Search">
            <button value="Search" class="btn btn-outline-success my-2 my-sm-0" type="submit" formmethod="get">Search</button>
            <%= link_to 'New Load Test', new_load_test_path, class: "btn btn-primary" %>
          </div>
        </div>
    </div>
</form>
  <div class="table-responsive">
    <table class="table table-sm table-hover text-center">
      <thead class="thead-dark">
      <tr>
        <th>Script</th>
        <th>Squad</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @load_tests.each do |load_test| %>
        <tr>
          <td><%= load_test.jmx_name %></td>
          <td><%= load_test.squad %></td>
          <td>
            <%= link_to 'Show', load_test_path(load_test), class: "btn btn-primary" %>
            <%= link_to 'Edit', edit_load_test_path(load_test), class: "btn btn-secondary" %>
            <%= link_to 'Delete', load_test_path(load_test),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: "btn btn-danger"
            %>
          </td>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>
    <div class="container">
        <%= will_paginate @load_tests, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center), previous_label: "Previous", next_label: "Next" %>
    </div>
  </div>
</div>

app/views/load_tests/new.html.erb
<div class="container mt-2 pb-3">
  <div class="col-sm pb-4">
    <h2 class="text-left">Add New Load Test</h2>
  </div>
  <%= form_with scope: :load_test, url: load_tests_path, local: true do |form| %>

    <div class="form-group">
      <%= form.label :jmx_id, "Choose JMX file" %>
      <%= form.select "jmx_id", Jmx.all.collect {|jmx| [jmx.name, jmx.id]}, {}, class: "form-control custom-select }" %>
    </div>

    <div class="form-group">
      <%= form.label :csv, "Choose CSV file" %>
      <div class="custom-file">
        <%= form.file_field :csv, class: "custom-file-input" %>
        <label class="custom-file-label" for="csvFile">Choose CSV file</label>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :Threshold %>
      <%= form.text_field :threshold, class: "form-control", placeholder: "in milliseconds" %>
    </div>

    <div class="form-group">
      <%= form.label :squad %>
      <%= form.text_field :squad, class: "form-control", placeholder: "Squad" %>
    </div>

    <div class="form-group">
      <%= form.label :telegram_id, "Telegram ID" %>
      <%= form.text_field :telegram_id, class: "form-control", placeholder: "Note" %>
    </div>

    <div class="form-group">
      <%= form.label :note %>
      <%= form.text_area :note, class: "form-control", placeholder: "Note" %>
    </div>

    <%= form.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/load_tests/show.html.erb
<div class="container mt-2">
  <p>
  <strong>JMX Name:</strong>
  <%= @load_test.jmx_name %>
  </p>

  <p>
  <strong>CSV:</strong>
  <%= @load_test.csv.filename if @load_test.csv.attached? %>
  </p>

  <p>
  <strong>Threshold:</strong>
  <%= @load_test.threshold %>
  </p>

  <p>
  <strong>Squad:</strong>
  <%= @load_test.squad %>
  </p>

  <p>
  <strong>Telegram ID:</strong>
  <%= @load_test.telegram_id %>
  </p>

  <p>
  <strong>Note:</strong>
  <%= @load_test.note %>
  </p>

  <div class="table-responsive">
    <table class="table table-sm table-hover text-center">
      <thead class="thead-dark">
        <tr>
          <th scope="col">No.</th>
          <th scope="col">Label</th>
          <th scope="col">Samples</th>
          <th scope="col">Average</th>
          <th scope="col">90%</th>
          <th scope="col">Previous 90%</th>
          <th scope="col">Min</th>
          <th scope="col">Max</th>
          <th scope="col">Error Rate</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        <% @load_test_reports.each do |load_test_report| %>
          <tr>
            <th scope="row"><%= load_test_report.id %></th>
            <td><%= load_test_report.label%></td>
            <td><%= load_test_report.samples%></td>
            <td><%= load_test_report.average%></td>
            <td><%= load_test_report.percentile_90%></td>
            <td><%= load_test_report.percentile_90_previous%></td>
            <td><%= load_test_report.min%></td>
            <td><%= load_test_report.max%></td>
            <td><%= load_test_report.error_rate %></td>
            <td><%= load_test_report.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to 'Back', load_tests_path, class: "btn btn-primary" %>
  <%= link_to 'Delete', load_test_path(@load_test),
    method: :delete,
    data: { confirm: 'Are you sure?' },
    class: "btn btn-danger"
  %>

</div>